# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - LightspeedDelivery

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lightspeeddelivery.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_648274078a6d4f2c918f762095a4a2b2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2b8854ccab74464680b674fdf33978c1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lightspeeddelivery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_648274078a6d4f2c918f762095a4a2b2 }}/lightspeed-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'LightspeedDelivery'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_78a680816ca8409fba1b9cf8a62ea52c }}
        images: 'lightspeeddelivery.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_648274078a6d4f2c918f762095a4a2b2 }}/lightspeed-image:${{ github.sha }}'